- name: Remove Workshop and Cache symlinks
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ steam_home }}/Cache"
  - "{{ steam_home }}/Workshop"

- name: Remove KF2
  file:
    path: "{{ steam_home }}/{{ item }}"
    state: absent
  loop:
  - "Steam"
  - ".steam"
  when: skip_kfgame != True

- name: Remove killinuxfloor packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - killinuxfloor-balance

- name: Remove killinuxfloor repo
  file:
    path: /etc/yum.repos.d/killinuxfloor.repo
    state: absent
  register: klf_repo

- name: Update yum cache
  yum:
    update_cache: yes
  when: klf_repo.changed
