- name: Add .NET Core repo
  template:
    src: microsoft-prod.repo.j2
    dest: /etc/yum.repos.d/microsoft-prod.repo

- name: Install .NET Core runtime
  yum:
    name: "dotnet-runtime-{{ dotnet_version }}"
    state: latest

- name: Obtain DepotDownloader
  get_url:
    url: "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_{{ depotdownloader_version }}/depotdownloader-{{ depotdownloader_version }}.zip"
    dest: "{{ steam_home }}/depotdownloader.zip"
    owner: steam
    group: steam
    mode: '0644'
  register: dd_dl

- name: Remove old DepotDownloader
  file:
    path: "{{ steam_home }}/depotdownloader"
    state: absent
  when: dd_dl.changed

- name: Create DepotDownloader directory
  file:
    path: "{{ steam_home }}/depotdownloader"
    state: directory
    owner: steam
    group: steam
    mode: '0755'

- name: Extract DepotDownloader
  unarchive:
    src: "{{ steam_home }}/depotdownloader.zip"
    dest: "{{ steam_home }}/depotdownloader"
  when: dd_dl.changed

- name: Install Killing Floor 2 Classic (be patient, 16 GB+)
  command: "{{ steam_home }}/depotdownloader/depotdownloader -app 232130 -depot 232131 -manifest 2346945547354693824 -validate -os linux -max-downloads 32 -dir {{ steam_home }}/Steam/KF2Server"
  no_log: True
  become: yes
  become_user: steam
  register: kf2_install
  changed_when: (kf2_installed_str not in kf2_install.stdout)

- name: Make KF2 executable
  file:
    path: "{{ steam_home }}/Steam/KF2Server/Binaries/Win64/KFGameSteamServer.bin.x86_64"
    mode: '0755'
