- name: Create Steam bin directory
  file:
    path: "{{ steam_home }}/bin"
    state: directory
    owner: steam
    group: steam

- name: Obtain killinuxfloor sources
  become: yes
  become_user: steam
  git:
    repo: https://github.com/bviktor/killinuxfloor.git
    dest: "{{ steam_home }}/killinuxfloor"
    force: yes

- name: Enable killinuxfloor commands
  file:
    src: "{{ item.target }}"
    dest: "{{ item.link }}"
    state: link
    force: yes
    owner: steam
    group: steam
  loop:
  - { target: '{{ steam_home }}/killinuxfloor/share/killinuxfloor', link: '{{ steam_home }}/bin/killinuxfloor' }
  - { target: '{{ steam_home }}/bin/killinuxfloor', link: '{{ steam_home }}/bin/klf' }
