- include_tasks: fail.yml
  vars:
  - errmsg: 'killinuxfloor supports CentOS 7 and 8 only.'
  when: (ansible_distribution_major_version != '7') and (ansible_distribution_major_version != '8')

# don't install stream, the new kernel is already in base
# and stream breaks libstdc++.i686 install over some file conflicts
# the x86_64 version (8.4) is different from the i686 (8.3) on some systems
# https://www.mail-archive.com/centos@centos.org/msg136831.html
#- name: Enable CentOS Release stream
#  yum:
#    name: centos-release-stream
#    state: latest
#  when: ansible_distribution_major_version == '8'

- name: Make sure the OS is up-to-date
  yum:
    name: '*'
    state: latest

- include_tasks: fail.yml
  vars:
  - errmsg: 'Due to a bug in the running kernel version, you must reboot before the installation of killinuxfloor can continue.'
  when: (ansible_distribution_major_version == '8') and (ansible_facts['kernel'] is version('4.18.0-147', '<'))

- name: Check the state of system services
  service_facts:

# we don't need to deal with autokick, the unit stops if kf2 stops
- name: Make sure the KF2 service isn't running
  systemd:
    name: kf2
    state: stopped
  when: ansible_facts.services["kf2.service"] is defined
