- include_tasks: fail.yml
  vars:
  - errmsg: 'killinuxfloor supports CentOS 7 and 8 only.'
  when: (ansible_distribution_major_version != '7') and (ansible_distribution_major_version != '8')

- name: Make sure the OS is up-to-date
  yum:
    name: '*'
    state: latest

- name: Check the state of system services
  service_facts:

# we don't need to deal with autokick, the unit stops if kf2 stops
- name: Make sure the KF2 service isn't running
  systemd:
    name: kf2
    state: stopped
  when: ansible_facts.services["kf2.service"] is defined and ansible_facts.services["kf2.service"].state == "running"
