- include_tasks: fail.yml
  vars:
  - errmsg: 'killinuxfloor supports CentOS 7 and 8 only.'
  when: (ansible_distribution_major_version != '7') and (ansible_distribution_major_version != '8')

- name: Make sure the OS is up-to-date
  yum:
    name: '*'
    state: latest
